//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace myTBsys.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_SH_Teacher
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T_SH_Teacher()
        {
            this.T_TB_TeachingTask = new HashSet<T_TB_TeachingTask>();
            this.T_TB_TeaYuding = new HashSet<T_TB_TeaYuding>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Password { get; set; }
        public string TelPhone { get; set; }
        public int IsHead { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_TB_TeachingTask> T_TB_TeachingTask { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_TB_TeaYuding> T_TB_TeaYuding { get; set; }
    }
}
