//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace myTBsys.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_SH_Class
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T_SH_Class()
        {
            this.T_SH_Student = new HashSet<T_SH_Student>();
            this.T_TB_Fenfa = new HashSet<T_TB_Fenfa>();
            this.T_TB_TeachingTask = new HashSet<T_TB_TeachingTask>();
            this.T_TB_StoreTable = new HashSet<T_TB_StoreTable>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int MajorId { get; set; }
    
        public virtual T_SH_Major T_SH_Major { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_SH_Student> T_SH_Student { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_TB_Fenfa> T_TB_Fenfa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_TB_TeachingTask> T_TB_TeachingTask { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_TB_StoreTable> T_TB_StoreTable { get; set; }
    }
}
