//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace myTBsys.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_TB_TeachingTask
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T_TB_TeachingTask()
        {
            this.T_TB_Choose = new HashSet<T_TB_Choose>();
            this.T_TB_StoreTable = new HashSet<T_TB_StoreTable>();
            this.T_TB_StuYuding = new HashSet<T_TB_StuYuding>();
            this.T_TB_TeaYuding = new HashSet<T_TB_TeaYuding>();
        }
    
        public int Id { get; set; }
        public string CourseId { get; set; }
        public string CourseName { get; set; }
        public string WeekTime { get; set; }
        public Nullable<double> Score { get; set; }
        public string CourseNature { get; set; }
        public string CourseType { get; set; }
        public string TotalTime { get; set; }
        public string LectureTime { get; set; }
        public string ExpTime { get; set; }
        public string MachineTime { get; set; }
        public string SEweek { get; set; }
        public string TeacherId { get; set; }
        public string IsMix { get; set; }
        public Nullable<int> DepartmentId { get; set; }
        public Nullable<int> AcademyId { get; set; }
        public int ClassId { get; set; }
        public Nullable<int> StuNum { get; set; }
        public string Description { get; set; }
        public int State { get; set; }
        public string Semeter { get; set; }
    
        public virtual T_SH_Academy T_SH_Academy { get; set; }
        public virtual T_SH_Class T_SH_Class { get; set; }
        public virtual T_SH_Department T_SH_Department { get; set; }
        public virtual T_SH_Teacher T_SH_Teacher { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_TB_Choose> T_TB_Choose { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_TB_StoreTable> T_TB_StoreTable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_TB_StuYuding> T_TB_StuYuding { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_TB_TeaYuding> T_TB_TeaYuding { get; set; }
    }
}
