//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace myTBsys.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TBsysEntities : DbContext
    {
        public TBsysEntities()
            : base("name=TBsysEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<T_QT_Other> T_QT_Other { get; set; }
        public virtual DbSet<T_SH_Academy> T_SH_Academy { get; set; }
        public virtual DbSet<T_SH_Class> T_SH_Class { get; set; }
        public virtual DbSet<T_SH_Department> T_SH_Department { get; set; }
        public virtual DbSet<T_SH_Major> T_SH_Major { get; set; }
        public virtual DbSet<T_SH_Student> T_SH_Student { get; set; }
        public virtual DbSet<T_SH_Teacher> T_SH_Teacher { get; set; }
        public virtual DbSet<T_SH_Workers> T_SH_Workers { get; set; }
        public virtual DbSet<T_TB_Books> T_TB_Books { get; set; }
        public virtual DbSet<T_TB_Choose> T_TB_Choose { get; set; }
        public virtual DbSet<T_TB_Fenfa> T_TB_Fenfa { get; set; }
        public virtual DbSet<T_TB_StoreTable> T_TB_StoreTable { get; set; }
        public virtual DbSet<T_TB_StuYuding> T_TB_StuYuding { get; set; }
        public virtual DbSet<T_TB_TeachingTask> T_TB_TeachingTask { get; set; }
        public virtual DbSet<T_TB_TeaYuding> T_TB_TeaYuding { get; set; }
    }
}
